name: Run R Markdown Workflow

on:
  push:
    branches:
      - master  # Change this to your main branch name
  pull_request:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.x'  # Specify the R version you need

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('readr', 'RSQLite', 'dplyr', 'chron', 'ggplot2'))"

      - name: Render R Markdown
        run: Rscript -e "rmarkdown::render('DataManagement31.Rmd')"

      - name: Commit rendered output
        uses: EndBug/add-and-commit@v7
        with:
          message: Rendered R Markdown output
          add: '*.html'
